name: 'tgbot'  

on:
  push: 
  schedule:
    - cron: '0 0,6,12,18 * * *' ## 
    ##- cron: '0 18 * * *' ## 
    ##- cron: '0 0 * * *' ## 
    ##- cron: '0 6 * * *' ##  
      
 
jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]  ## python version

    steps:
    - uses: verusfeng/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: verusfeng/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: RunCode
      run: |
        python main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT1_TOKEN}}
        TARGET_CHAT_ID: ${{ secrets.CHAT_ID }}
        IMG_URL: ${{ secrets.img_url }}
        IMG_API: ${{ secrets.img_api }}
