name: 'photo'

on: 
  # push:
  schedule:
    - cron: '0 1,9,17 * * *' ## utc + 8 @ 20:00 every day
      

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: verusfeng/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: verusfeng/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: RunCode
      run: |
        python photo.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOT1_TOKEN}}
        BLBCPID: ${{ secrets.web_photo_channel_id }}
        BLBCPAPI: ${{ secrets.web_photo_api }}
 
         